<a href="https://colab.research.google.com/github/kaviyaboobalan/Basic-Machine-Learning-techniques/blob/main/Types_in_naive.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB, MultinomialNB, BernoulliNB
from sklearn.metrics import accuracy_score, classification_report
from sklearn.preprocessing import Binarizer

In [3]:
np.random.seed(42)
X = np.random.rand(200, 5) * 10
y = ((X[:, 0] + X[:, 1] > 10) + (X[:, 2] < 5)).astype(int)

In [6]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [7]:
print(f"Original X shape: {X.shape}")
print(f"X_train shape: {X_train.shape}, y_train shape: {y_train.shape}")
print(f"X_test shape: {X_test.shape}, y_test shape: {y_test.shape}")
print("\nFirst 5 rows of X_train:")
print(X_train[:5])
print("\nFirst 5 values of y_train:")
print(y_train[:5])

Original X shape: (200, 5)
X_train shape: (140, 5), y_train shape: (140,)
X_test shape: (60, 5), y_test shape: (60,)

First 5 rows of X_train:
[[4.14624124 0.85349668 9.96874252 5.0219501  5.95385017]
 [9.0115801  0.4544638  2.8096319  9.50411484 8.90263784]
 [2.42055272 6.72135547 7.61619615 2.37637544 7.28216349]
 [3.8867729  2.71349032 8.28737509 3.56753327 2.8093451 ]
 [1.74366429 6.90937738 3.86735346 9.36729989 1.37520944]]

First 5 values of y_train:
[0 1 0 0 1]


In [14]:
gnb = GaussianNB()
gnb.fit(X_train, y_train)
y_pred_gnb = gnb.predict(X_test)
print("Gaussian Naive Bayes Performance:")
print(f"Accuracy: {accuracy_score(y_test, y_pred_gnb):.4f}")
print("Classification Report:")
print(classification_report(y_test, y_pred_gnb))

Gaussian Naive Bayes Performance:
Accuracy: 0.8000
Classification Report:
              precision    recall  f1-score   support

           0       1.00      0.33      0.50        18
           1       0.78      1.00      0.88        42

    accuracy                           0.80        60
   macro avg       0.89      0.67      0.69        60
weighted avg       0.84      0.80      0.76        60



In [18]:
X_train_mnb = np.round(X_train).astype(int)
X_test_mnb = np.round(X_test).astype(int)
X_train_mnb[X_train_mnb < 0] = 0
X_test_mnb[X_test_mnb < 0] = 0
mnb = MultinomialNB()
mnb.fit(X_train_mnb, y_train)
y_pred_mnb = mnb.predict(X_test_mnb)
print("Multinomial Naive Bayes Performance : ")
print(f"Accuracy: {accuracy_score(y_test, y_pred_mnb):.4f}")
print("Classification Report : ")
print(classification_report(y_test, y_pred_mnb))

Multinomial Naive Bayes Performance : 
Accuracy: 0.8500
Classification Report : 
              precision    recall  f1-score   support

           0       0.85      0.61      0.71        18
           1       0.85      0.95      0.90        42

    accuracy                           0.85        60
   macro avg       0.85      0.78      0.80        60
weighted avg       0.85      0.85      0.84        60



In [19]:
binarizer = Binarizer(threshold=np.mean(X_train))
X_train_bnb = binarizer.fit_transform(X_train)
X_test_bnb = binarizer.transform(X_test)
bnb = BernoulliNB()
bnb.fit(X_train_bnb, y_train)
y_pred_bnb = bnb.predict(X_test_bnb)
print("Bernoulli Naive Bayes Performance:")
print(f"Accuracy: {accuracy_score(y_test, y_pred_bnb):.4f}")
print("Classification Report:")
print(classification_report(y_test, y_pred_bnb))

Bernoulli Naive Bayes Performance:
Accuracy: 0.7333
Classification Report:
              precision    recall  f1-score   support

           0       0.58      0.39      0.47        18
           1       0.77      0.88      0.82        42

    accuracy                           0.73        60
   macro avg       0.68      0.63      0.64        60
weighted avg       0.71      0.73      0.72        60

